debugMode: true

http:
  host: 0.0.0.0
  port: 8889
  useSSL: false
  sslDir: ssl
  cerFile: certificate.crt
  keyFile: private.key

controller:
  grpcHost: localhost
  grpcPort: 50051

updater:
  host: localhost
  grpcPort: 12305
  fileServerPort: 12306
  savePath: .
  unzipPath: .\\unzip
  uiFolderName: cookRobot-linux-arm64
  middlePlatformFilename: cook-robot-middle-platform-go
  controllerFilename: cook-robot-controller-go