debugMode: true

grpc:
  targetHost: "localhost"
  targetPort: 50051

http:
  host: "0.0.0.0"
  port: 8889

softwareUpdate:
#  serverHost: "http://localhost"
  serverHost: "http://124.71.146.83"
  serverPort: 12306
  filename: "test.zip"
  savePath: "."
  unzipPath: ".\\unzip"
  uiFolderName: "cookRobot-linux-arm64"
